export const LOADING_GET_LIST_CAT = 'LOADING_GET_LIST_CAT';
export const SUCCESS_GET_LIST_CAT = 'SUCCESS_GET_LIST_CAT';
export const FAILED_GET_LIST_CAT = 'FAILED_GET_LIST_CAT';

export const LOADING_FETCH_MORE_GET_LIST_CAT = 'LOADING_FETCH_MORE_GET_LIST_CAT';
export const SUCCESS_FETCH_MORE_GET_LIST_CAT = 'SUCCESS_FETCH_MORE_GET_LIST_CAT';
export const FAILED_FETCH_MORE_GET_LIST_CAT = 'FAILED_FETCH_MORE_GET_LIST_CAT';